from TestAuthor             import TestAuthor
from TestObservingType      import TestObservingType
from TestPressureWeight     import TestPressureWeight
from TestProposal           import TestProposal
from TestProposalType       import TestProposalType
from TestScientificCategory import TestScientificCategory
from TestSession            import TestSession
from TestStatus             import TestStatus
from TestTarget             import TestTarget
