#!/bin/bash
HOST=trent
echo Rebooting DB $1 ...

# We don't want to drop then create this DB because it may contain
# weather data
dropdb -h $HOST -U dss $1
createdb -h $HOST -U dss $1

# Instead, drop the tables that django knows about
#psql -U dss -d $1 < drop_model_tables.sql 
python manage.py syncdb
psql -h $HOST -U dss -d $1 < populate_db.sql
psql -h $HOST -U dss -d $1 < populate_auth_user.sql

echo DB $1 Rebooted.
