#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/dss/conundrum/gwt/gwt-linux-1.5.3/gwt-user.jar:/home/dss/conundrum/gwt/gwt-linux-1.5.3/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" edu.nrao.dss.Scheduler;
