from ElectiveHttpAdapter     import ElectiveHttpAdapter
from FriendHttpAdapter       import FriendHttpAdapter
from InvestigatorHttpAdapter import InvestigatorHttpAdapter
from PeriodHttpAdapter       import PeriodHttpAdapter
from ProjectHttpAdapter      import ProjectHttpAdapter
from SessionHttpAdapter      import SessionHttpAdapter
from WindowHttpAdapter       import WindowHttpAdapter 
from WindowRangeHttpAdapter  import WindowRangeHttpAdapter 
from UserHttpAdapter         import UserHttpAdapter 
