INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(null, 'Mustang', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(2, 'CGSR2', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(5, 'GASP', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(9, 'Radar', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(1, 'CCB', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(8, 'Mark V', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(null, 'Spigot', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(3, 'DCR', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(11, 'SP', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(4, 'ACS', 0, 0);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(6, 'GUPPI', 1, 1);
INSERT INTO calculator_backend (dss_backend_id, name, k1, k2) VALUES(null, 'Other', 1, 1);
