from TestElectiveResource      import TestElectiveResource
from TestFriendResource        import TestFriendResource
from TestInvestigatorResource  import TestInvestigatorResource
from TestPeriodResource        import TestPeriodResource
from TestProjectResource       import TestProjectResource
from TestSessionResource       import TestSessionResource
from TestUserResource          import TestUserResource
from TestWindowResource        import TestWindowResource
from TestWindowRangeResource   import TestWindowRangeResource
