from utils                     import *
from resources                 import *
from TestBlackout              import TestBlackout
from TestElective              import TestElective
from TestEmailTemplate         import TestEmailTemplate
from TestPeriod                import TestPeriod
from TestPeriodChanges         import TestPeriodChanges
from TestPeriodAccounting      import TestPeriodAccounting
from TestProject               import TestProject
from TestReceiver              import TestReceiver
from TestReceiverCompile       import TestReceiverCompile
from TestReceiverSchedule      import TestReceiverSchedule
from TestScheduleTools         import TestScheduleTools
from TestSemester              import TestSemester
from TestSesshun               import TestSesshun
from TestShiftPeriodBoundaries import TestShiftPeriodBoundaries
from TestTimeAccounting        import TestTimeAccounting
from TestUser                  import TestUser
from TestUtilities             import TestUtilities
from TestViews                 import TestViews
from TestViewsPTC              import TestViewsPTC
from TestWindow                import TestWindow
from TestWindowRange           import TestWindowRange
